# Generated by Django 4.0.3 on 2022-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
